POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
    "username" : "peggy",
    "password" : "peggylover1539"
}

###
POST http://localhost:3003/api/login/ HTTP/1.1
content-type: application/json

{
    "username" : "peggy",
    "password" : "wrongpassword"
}