const mongoose = require('mongoose')

if (process.argv.length < 3){
    console.log('Please provide password as argument')
    process.exit(1)
}
const db_password = process.argv[2]

const url = `mongodb+srv://cesaraguirrework_db_user:${db_password}@cluster0.orfcdkd.mongodb.net/?appName=Cluster0`

mongoose.set('strictQuery', false) // Mongoose will no longer filter out query filter properties that are not explicitly defined in your schema

mongoose.connect(url, {family: 4})

const personSchema = new mongoose.Schema({
    name: String,
    number: String,
    // id's are generated by MongoDB by default, so not needed
})

const Person = mongoose.model('Person', personSchema) // name of the model, schema

if (process.argv.length == 3){
    // fetch all the people in the db
    Person.find({}).then(result => {
        console.log('phonebook')
        result.forEach( person => {
            console.log(`${person.name} ${person.number}`)
        })
        mongoose.connection.close()
    })
} else if (process.argv.length >= 5){
    // add person into db
    const person = new Person({
        name: process.argv[3],
        number: process.argv[4]
    })

    person.save().then( result => {
        console.log(`added ${result.name} number ${result.number} to phonebook`)
        mongoose.connection.close()
    })
} else {
    console.log('Please provide a number argument for the intended user!')
    process.exit(1)
}